
services:
  tax_api:
    build: .
    container_name: tax_calculator
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - TAX_API_URL=http://tax_api_mock:5001/tax-calculator/
    depends_on:
      - tax_api_mock

  tax_api_mock:
    image: ptsdocker16/interview-test-server
    container_name: tax_api_mock
    restart: always
    ports:
      - "5001:5001"
